### PR TITLE
feat: Report test status

### PR DESCRIPTION
**Pull request by FeignClaims**
Report test passing and test coverage in README.

The test coverage report is supported by Codecov, thus requires @JinBridger to add the global token `CODECOV_TOKEN` as a repository secret from [the official website](https://about.codecov.io/).

After that, we can merge the pr.

### CODE REVIEW

**Comment by JinBridger** [comment]
@idawnlight PTAL

**Comment by idawnlight** [comment]
LGTM

**Comment by JinBridger** [comment]
https://github.com/tridoc-dev/tridoc/actions/runs/9140560681/job/25134026125 The action failed when upload report to codecov. PTAL @FeignClaims @idawnlight 

```
==> Uploader SHASUM verified (209d13481be406d6a2aa9519fa61c84883e3213308b5628c43a5e94cae75b8e6  codecov)
==> Running version v0.6.0
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov create-commit
info - 2024-05-18 14:28:[27](https://github.com/tridoc-dev/tridoc/actions/runs/9140560681/job/25134026125#step:9:28),735 -- ci service found: github-actions
warning - 2024-05-18 14:[28](https://github.com/tridoc-dev/tridoc/actions/runs/9140560681/job/25134026125#step:9:29):27,744 -- No config file could be found. Ignoring config.
info - 2024-05-18 14:28:27,817 -- Process Commit creating complete
error - 2024-05-18 14:28:27,817 -- Commit creating failed: {"detail":"You do not have permission to perform this action."}
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov create-report'
/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov create-report
info - 2024-05-18 14:28:28,567 -- ci service found: github-actions
warning - 2024-05-18 14:28:28,576 -- No config file could be found. Ignoring config.
info - 2024-05-18 14:28:28,681 -- Process Report creating complete
error - 2024-05-18 14:28:28,681 -- Report creating failed: {"detail":"You do not have permission to perform this action."}
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov do-upload'
/home/runner/work/_actions/codecov/codecov-action/v4.0.1/dist/codecov do-upload
info - 2024-05-18 14:28:[29](https://github.com/tridoc-dev/tridoc/actions/runs/9140560681/job/25134026125#step:9:30),431 -- ci service found: github-actions
warning - 2024-05-18 14:28:29,439 -- No config file could be found. Ignoring config.
warning - 2024-05-18 14:28:29,445 -- xcrun is not installed or can't be found.
warning - 2024-05-18 14:28:29,711 -- No gcov data found.
warning - 2024-05-18 14:28:29,711 -- coverage.py is not installed or can't be found.
info - 2024-05-18 14:28:29,726 -- Found 2 coverage files to report
info - 2024-05-18 14:28:29,726 -- > /home/runner/work/tridoc/tridoc/coverage.xml
info - 2024-05-18 14:28:29,726 -- > /home/runner/work/tridoc/tridoc/.github/workflows/coverage-test.yaml
info - 2024-05-18 14:28:29,807 -- Process Upload complete
error - 2024-05-18 14:28:29,807 -- Upload failed: {"detail":"You do not have permission to perform this action."}
```

related: https://github.com/codecov/codecov-action/issues/1273

**Comment by JinBridger** [comment]
Didn't get any ideas on this error... 🤔

**Comment by FeignClaims** [comment]
> The action failed when upload report to codecov.

Have you added the global token `CODECOV_TOKEN` as a repository secret from [Codecov: tridoc-dev/tridoc](https://app.codecov.io/github/tridoc-dev/tridoc/settings)? I have no permission to add the token, but it is required in the workflow:

```yaml

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
```

**Comment by idawnlight** [comment]
Updated the `CODECOV_TOKEN` from the codecov repo settings and seemed to fix this.

**Comment by JinBridger** [comment]
> > The action failed when upload report to codecov.
> 
> Have you added the global token `CODECOV_TOKEN` as a repository secret from [Codecov: tridoc-dev/tridoc](https://app.codecov.io/github/tridoc-dev/tridoc/settings)? I have no permission to add the token, but it is required in the workflow:
> 
> ```yaml
> - name: Upload coverage reports to Codecov
>   uses: codecov/codecov-action@v4.0.1
>   with:
>     token: ${{ secrets.CODECOV_TOKEN }}
> ```

Got it. Looks like we need the REAL OWNER of this repo to add the secret...😂

**Pull request merged**
